### ISSUE TITLE
Please support Python 3.x

### ISSUE THREAD

**Issue by Sembazuru** [Jeff-Ciesielski/Boms-Away#19]
I've transitioned to 3.x and want to avoid the confusion of both 3.x and 2.x on my system. As such I eschew 2.x only python projects.

**Comment by Jeff-Ciesielski** [comment]
Closed by https://github.com/Jeff-Ciesielski/Boms-Away/commit/7c6775c55e2b07cb52a085cd4a34f20be3526498
