### ISSUE TITLE
very minor issue: label mispelled

### ISSUE THREAD

**Issue by easyw** [Jeff-Ciesielski/Boms-Away#20]
in line 82 of file bomsaway.py there is a mispelled word
_82:_   comp_label = wx.StaticText(self, -1, '**Componenents**', style=wx.ALIGN_CENTER_HORIZONTAL)

**Comment by Jeff-Ciesielski** [comment]
Closed by https://github.com/Jeff-Ciesielski/Boms-Away/commit/05e68559e3ab14c3e27d5e1b06d8ce529c5bf8c6

Meta: You misspelled `mispelled`.  

![image](http://www.reactiongifs.com/r/2013/01/BURN.gif)

;) (thanks for the issue)
