### ISSUE TITLE
bug in lookup

### ISSUE THREAD

**Issue by macsimski** [Jeff-Ciesielski/Boms-Away#21]
On some parts, i get this error:

`Traceback (most recent call last):
  File "./bomsaway.py", line 161, in on_lookup_component
    dlg = wx.MessageDialog(parent,
NameError: global name 'parent' is not defined`

but on others without parts in the database i get a normal window "component does not exists in datastore"

**Comment by ghost** [comment]
Change line 161 in bomsaway.py to:
 dlg = wx.MessageDialog(self.parent,

**Comment by macsimski** [comment]
thanks! will try this evening.

**Comment by Jeff-Ciesielski** [comment]
Should be fixed by https://github.com/Jeff-Ciesielski/Boms-Away/commit/0e481cbc91f064acb52b67ba0a5d6ac2c1852879

Let me know if you continue to have issues :)
